### ISSUE TITLE
Using unknown proof.type in json-ld VC with multiple proofs

### ISSUE THREAD

**Issue by pstuermlinger** [sicpa-dlab/aries-cloudagent-python#134]
## What
Given your feature/multiple-proof branch merged into upstream (0.7.4-rc2, see [here](https://github.com/pstuermlinger/aries-cloudagent-python/tree/0.7.4-rc2-multi-proofs)) I want to issue a credential already decorated with a proof unknown to aca-py (e.g. an eIDAS signature).

An example is:
```json
{
   "credential":{
      "@context":[
         "https://www.w3.org/2018/credentials/v1",
         "https://w3id.org/citizenship/v1"
      ],
      "credentialSubject":{
         "familyName":"SMITH",
         "gender":"Male",
         "givenName":"JOHN",
         "type":[
            "PermanentResident",
            "Person"
         ]
      },
      "proof":{
         "type":"CAdESRSASignature2020",
         "proofPurpose":"assertionMethod",
         "created":"2019-08-23T20:21:34Z",
         "verificationMethod":"did:factom:5d0dd58757119dd437c70d92b44fbf86627ee275f0f2146c3d99e441da342d9f#MIIEEzCCAvugAwIBAgIUJ0hTJswF5BBreQgbEQL8FTLXwHAwDQYJKoZIhvcNAQELBQAwgZgxCzAJBgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZC1Ib2xsYW5kMRIwEAYDVQQHDAlBbXN0ZXJkYW0xFDASBgNVBAoMC1Rlc3RDb21wYW55MQswCQYDVQQLDAJJVDEVMBMGA1UEAwwMU2NvdHQgTWFsbGV5MSMwIQYJKoZIhvcNAQkBFhRzbWFsbGV5QHNwaGVyZW9uLmNvbTAeFw0yMDEyMDIxNDMxMDVaFw0zMDExMzAxNDMxMDVaMIGYMQswCQYDVQQGEwJOTDEWMBQGA1UECAwNTm9vcmQtSG9sbGFuZDESMBAGA1UEBwwJQW1zdGVyZGFtMRQwEgYDVQQKDAtUZXN0Q29tcGFueTELMAkGA1UECwwCSVQxFTATBgNVBAMMDFNjb3R0IE1hbGxleTEjMCEGCSqGSIb3DQEJARYUc21hbGxleUBzcGhlcmVvbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkZfqj459pkdt5GLelamSySQP3owkyYOXW1NLTLr3dC_RzE8x3SRpHQwaRErm0VYvV35JVvubGZgatm5SNsTUHw7Ywrwy-hGFCXo2JOabL0lj3EpkpRPpVS7GXAlMxTvfZihw8IgmA3ZEnhnCYbyfKiCAOmVGLc_dViFTUuk2O6t6gkAdL0MhzU6nCBBariqlwWQxXf7z-nFubBrBio2l_GL6Pf6orvB_67V2PQEYnYlf24VtfdV34_QcU3T9bQjN2RhSzT9HYrYZtEXEmS4ARaN4mSoCnkITNsrGUz3LpX0ozxk2kQCUe89v8TUd-uYzA_sHXJXa7oHqTA1ZJVrtDAgMBAAGjUzBRMB0GA1UdDgQWBBT2b43zVAuqVWwFIZLSTSOdI3n5IDAfBgNVHSMEGDAWgBT2b43zVAuqVWwFIZLSTSOdI3n5IDAPBgNVHRMBAf8EBTADAQH_MA0GCSqGSIb3DQEBCwUAA4IBAQBnKynE3w04FyEHpYJs94eYrvKAgH6lvavHlDbiZxq1YgPwQN7lbFKIyZxsfcx1QGu1Rk_e-B7D-peIYGtL0-lQxbC88ogh03CaPqrJEhhmSxLEN-L3HQl-pItVUTKH8kaxHeC86ym2pOEJW2y7mVtPYkrgMiTjmOJj60hJEQE87VT_TB_soAXOm8oVXy1Ha3HwHZ4vouG_SwYhXWaqnOUDOifR579Cy53sMkuG0m7SuXxOZp20jnX7TaR8ElH8mZifTSBjkT2RNj1QhFG-Tl5nR_Q63j4xIw9f2Sj-jVclsuIcEQh00bo8pfdMhA-sMX1zCsOvG3sDnsfsqLmL7guV",
         "cades":"-----BEGIN PKCS7----- iG9w0BCRABCaB0MHICAQAwDQYLK... -----END PKCS7-----"
      },
      "description":"Government of Example Permanent Resident Card.",
      "identifier":"83627465",
      "issuanceDate":"2019-12-03T12:19:52Z",
      "issuer":"did:key:zUC...",
      "name":"Permanent Resident Card",
      "type":[
         "VerifiableCredential",
         "PermanentResidentCard"
      ]
   },
   "options":{
      "proofType":"BbsBlsSignature2020"
   }
}
```

By sending this (as part of the credential offer) to `/issue-credential-2.0/send` the process fails because the json-ld handler drops the proof content:

```
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 667, in credential_exchange_send
    auto_remove=auto_remove,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 84, in prepare_send
    comment="create automated v2.0 credential exchange record",
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 230, in create_offer
    cred_proposal_message
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py", line 412, in create_offer
    f"{len(missing_properties)} attributes dropped. "
aries_cloudagent.vc.ld_proofs.error.LinkedDataProofException: 4 attributes dropped. Provide definitions in context to correct. ['proof.proofPurpose', 'proof.verificationMethod', 'proof.created', 'proof.cades']
2022-05-20 16:50:49,097 aries_cloudagent.admin.server ERROR Handler error with exception: 4 attributes dropped. Provide definitions in context to correct. ['proof.proofPurpose', 'proof.verificationMethod', 'proof.created', 'proof.cades']

=================
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 159, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 196, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 293, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 384, in setup_context
    return await task
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 667, in credential_exchange_send
    auto_remove=auto_remove,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 84, in prepare_send
    comment="create automated v2.0 credential exchange record",
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 230, in create_offer
    cred_proposal_message
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py", line 412, in create_offer
    f"{len(missing_properties)} attributes dropped. "
aries_cloudagent.vc.ld_proofs.error.LinkedDataProofException: 4 attributes dropped. Provide definitions in context to correct. ['proof.proofPurpose', 'proof.verificationMethod', 'proof.created', 'proof.cades']
2022-05-20 16:50:49,098 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 159, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 196, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 293, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 384, in setup_context
    return await task
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 667, in credential_exchange_send
    auto_remove=auto_remove,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 84, in prepare_send
    comment="create automated v2.0 credential exchange record",
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 230, in create_offer
    cred_proposal_message
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py", line 412, in create_offer
    f"{len(missing_properties)} attributes dropped. "
aries_cloudagent.vc.ld_proofs.error.LinkedDataProofException: 4 attributes dropped. Provide definitions in context to correct. ['proof.proofPurpose', 'proof.verificationMethod', 'proof.created', 'proof.cades']
```

However, when I replace the proof with one of type Ed25519Signature2018 it succeeds:
```json
"proof": {
        "proofPurpose": "assertionMethod",
        "created": "2019-12-11T03:50:55",
        "type": "Ed25519Signature2018",
        "verificationMethod": "did:key:z6Mkgg342Ycpuk263R9d8Aq6MUaxPn1DDeHyGo38EefXmgDL#z6Mkgg342Ycpuk263R9d8Aq6MUaxPn1DDeHyGo38EefXmgDL",
        "jws": "eyJhbGciOiAiRWREU0EiLCAiYjY0IjogZmFsc2UsICJjcml0IjogWyJiNjQiXX0..Q6amIrxGiSbM7Ce6DxlfwLCjVcYyclas8fMxaecspXFUcFW9DAAxKzgHx93FWktnlZjM_biitkMgZdStgvivAQ",
    }
```

Do you have any idea what's happening here and why?
According to #112  I expected the unknown proof type to be skipped.

Bonus question: why haven't you created a PR to merge multi-proofs into upstream, yet?

Kind regards
Patrick

**Comment by pstuermlinger** [comment]
Could fix it by adding another context:
https://gitlab.grnet.gr/essif-lab/interoperability/ssi-eidas-bridge/-/raw/master/public/contexts/ades-signatures.jsonld
